# Generated by Django 5.0.1 on 2024-03-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='costo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='detalle',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
